### PR TITLE
Feature/microcredit

### LINKED ISSUE #133: micro-credit base smart-contract

### PR DESCRIPTION
**Pull request by dumedco**
fixes #133

### CODE REVIEW

**Review by obernardovieira — COMMENTED** [review]
Can we remove the deployments/solcInputs folder, or do we need it?
What is the `CouncilProxyAdmin` for? Is it the admin of microcreditproxy? Doesn't it need an implementation?

**Comment by dumedco** [comment]
> Can we remove the deployments/solcInputs folder, or do we need it? What is the `CouncilProxyAdmin` for? Is it the admin of microcreditproxy? Doesn't it need an implementation?

We cannot remove the solcInputs folder. It is used by hardhat. In these files are saved the latest deployed versions of the contracts. So hardhat uses this files to know when a contracts has been changed

**Comment by dumedco** [comment]
> What is the `CouncilProxyAdmin` for? Is it the admin of microcreditproxy? Doesn't it need an implementation?

Yes, I know the naming is confusing a little bit. there are two types of proxies:
- "normal proxy", like CommunityAdminProxy, DonationMinerProxy, DepositProxy etc and now also MicrocreditProxy. the scope of this type of proxy if to be used as a 'pointer' for the implementation
- proxyAdmin - like ImpactProxyAdmin and now CouncilProxyAdmin  - e special type of contract (that is not upgradeable and doesn't need an implementation). The only scope of this contract is to upgrade the implementation of the "normal proxies".. ImpactProxyAdmin is in charge of updating the implementation for CommunityAdminProxy, DonationMinerProxy, DepositProxy, etc. The owner of the ImpactProxyAdmin is the DAO so only the DAO can upgrade the implementation of these contracts (by using the ImpactProxyAdmin).

**Comment by obernardovieira** [comment]
Wait, I've forgotten about one thing. When a loan manager adds a user, that user should have X amount of time to claim the loan. If after that the loan isn't claimed, then the loan manager can add the user again with the same or different parameters. While there is one loan that can be claimed, it shouldn't be possible to add the same user again.

**Pull request merged**
